App/urls.py
from django.conf.urls import url, include

from App import views

urlpatterns=[
    url(r'^home/',views.home,name='home'),
    url(r'^market/', views.market, name='market'),
    url(r'^marketwithparams/(?P<typeid>\d+)/(?P<childcid>\d+)/(?P<order_rule>\d+)/',
        views.market_with_params,name='market_with_params'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^register/',views.register,name='register'),
    url(r'^login/',views.login,name='login'),
    url(r'^checkuser/',views.check_user,name='check_user'),
    url(r'^logout/',views.logout,name='logout'),
    url(r'^sendemail/',views.send_email,name='send_email'),
    url(r'^addtocart/',views.add_to_cart,name='add_to_cart'),
    url(r'^subtocart/',views.sub_to_cart,name='sub_to_cart'),
    url(r'^changecartstate/',views.change_cart_state,name='change_cart_state'),
    url(r'^subshopping/',views.sub_shopping,name='sub_shopping'),
    url(r'^allselect/',views.all_select,name='all_select'),
    url(r'^makeorder/',views.make_order,name='make_order'),
    url(r'^orderdetail/',views.order_detail,name='order_detail'),
    url(r'^orderlistnotpay/',views.order_list_not_pay,name='order_list_not_pay'),
    url(r'^payed/',views.payed,name='payed'),
]

aimosxw/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sxw/',include('App.urls',namespace='sxw')),
]

App/models.py
from django.db import models

# Create your models here.
from App.views_constant import ORDER_STATUS_NOT_PAY


class Main(models.Model):
    img = models.CharField(max_length=255)
    name=models.CharField(max_length=64)
    trackid = models.IntegerField(default=1)

    class Meta:
        abstract=True

class MainWheel(Main):
    class Meta:
        db_table = 'sxw_wheel'

class MainNav(Main):
    class Meta:
        db_table = 'sxw_nav'

class MainMustBuy(Main):
    class Meta:
        db_table='sxw_mustbuy'

class MainShop(Main):
    class Meta:
        db_table='sxw_shop'

class MainShow(Main):
    """
    categoryid,brandname,img1,childcid1,productid1,longname1,price1,marketprice1,
    img2,childcid2,productid2,longname2,price2,marketprice2,img3,childcid3,
    productid3,longname3,price3,marketprice3
    """
    categoryid=models.IntegerField(default=1)
    brandname=models.CharField(max_length=64)
    img1=models.CharField(max_length=255)
    childcid1=models.IntegerField(default=1)
    productid1=models.IntegerField(default=1)
    longname1=models.CharField(max_length=128)
    price1=models.IntegerField(default=1)
    marketprice1=models.IntegerField(default=1)
    img2=models.CharField(max_length=255)
    childcid2=models.IntegerField(default=1)
    productid2=models.IntegerField(default=1)
    longname2=models.CharField(max_length=128)
    price2=models.IntegerField(default=1)
    marketprice2=models.IntegerField(default=1)
    img3=models.CharField(max_length=255)
    childcid3=models.IntegerField(default=1)
    productid3=models.IntegerField(default=1)
    longname3=models.CharField(max_length=128)
    price3=models.IntegerField(default=1)
    marketprice3=models.IntegerField(default=1)
    class Meta:
        db_table='sxw_mainshow'

class FoodType(models.Model):
    typeid=models.IntegerField(default=1)
    typenames=models.CharField(max_length=32)
    childtypenames=models.CharField(max_length=255)
    typesort=models.IntegerField(default=1)
    class Meta:
        db_table='sxw_foodtype'

class Goods(models.Model):

    productid=models.IntegerField(default=1)
    productimg=models.CharField(max_length=255)
    productname=models.CharField(max_length=128)
    productlongname=models.CharField(max_length=255)
    isxf=models.BooleanField(default=False)
    pmdesc=models.BooleanField(default=False)
    specifics=models.CharField(max_length=64)
    price=models.FloatField(default=0)
    marketprice=models.FloatField(default=0)
    categoryid=models.IntegerField(default=1)
    childcid=models.IntegerField(default=1)
    childcidname=models.CharField(max_length=128)
    dealerid=models.IntegerField(default=1)
    storenums=models.IntegerField(default=1)
    productnum=models.IntegerField(default=1)
    class Meta:
        db_table='axf_goods'

class User(models.Model):
    u_username=models.CharField(max_length=32,unique=True)
    u_password=models.CharField(max_length=256)
    u_email=models.CharField(max_length=64,unique=True)
    u_icon=models.ImageField(upload_to='icons/%Y/%m/%d')
    is_active=models.BooleanField(default=False)
    is_delete=models.BooleanField(default=False)

    class Meta:
        db_table='sxw_user'

class Cart(models.Model):
    c_user=models.ForeignKey(User)
    c_goods=models.ForeignKey(Goods)

    c_goods_num=models.IntegerField(default=1)
    c_is_select=models.BooleanField(default=True)
    class Meta:
        db_table = 'sxw_cart'

class Order(models.Model):
    o_user=models.ForeignKey(User)
    o_price=models.FloatField(default=0)
    o_time=models.DateTimeField(auto_now=True)
    o_status=models.IntegerField(default=ORDER_STATUS_NOT_PAY)

    class Meta:
        db_table='sxw_order'

class OrderGoods(models.Model):
    o_order=models.ForeignKey(Order)
    o_goods=models.ForeignKey(Goods)
    o_goods_num=models.IntegerField(default=1)

    class Meta:
        db_table='sxw_ordergoods'

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    {% block ext_css %}
    {% endblock %}
</head>
<body>
{% block header %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}
<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
{% block ext_js %}

{% endblock %}
</body>
</html>

templates/base_main.html
{% extends 'base.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
{% endblock %}

{% block header %}
    <header></header>
{% endblock%}

{% block footer %}
    <footer>
        <a href="{% url 'sxw:home'%}" class="home">
            <dl>
                <dt>
                    <span>

                    </span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'sxw:market'%}" class="market">
            <dl>
                <dt>
                    <span>

                    </span>
                </dt>
                <dd>超市</dd>
            </dl>
        </a>
        <a href="{% url 'sxw:cart'%}" class="cart">
            <dl>
                <dt>
                    <span>

                    </span>
                </dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a href="{% url 'sxw:mine'%}" class="mine_icon">
            <dl>
                <dt>
                    <span>

                    </span>
                </dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
{% endblock%}

templates/base_order.html
{% extends 'base.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'main/css/order.css' %}">
{% endblock %}

{% block header %}
    <header></header>
{% endblock %}

templates/base_user.html
{% extends 'base.html' %}
{% load static %}

{% block ext_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'user/css/user.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'main/js/md5.js' %}"></script>
{% endblock %}


{% block header %}
<header>

</header>
{% endblock %}

templates/cart.html
{% extends 'base_main.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'main/css/cart.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'main/js/cart.js'%}"></script>

{% endblock%}

{% block content %}
<div id="cart">
    <h3>购物车</h3>
    <div class="full">
        <section>
            <ul>
                <li>收货人：aimo</li>
                <li>电话：110</li>
                <li>地址：杭州西湖里</li>
            </ul>
            <section class="bill">
                <p>闪送超市</p>
                <p>¥0起送,22:00前满¥30免运费</p>
                <a href="#">凑单专区</a>
            </section>


            <section class="delivery">
                <span>收货时间</span>
                <span>一小时送达</span>
                <a href="#">可预订></a>
            </section>
            <section class="delivery">
                <span>收货备注</span> <input type="text" placeholder="可输入100字以内特殊要求内容"/>
            </section>
            <ul>
                {% for cart in carts %}
                    <li class="menulist" cartid="{{ cart.id }}">
                        <div class="confirm">
                            <span>
                                {% if cart.c_is_select %}
                                <span>√</span>
                                {% else %}
                                <span></span>
                                {% endif %}
                            </span>
                        </div>
                        <a href="#">
                            <img src="{{ cart.c_goods.productimg }}" alt="{{cart.c_goods.productlongname}}">
                        <p>{{cart.c_goods.productlongname }}</p>
                            <p class="presentPrice">{{cart.c_goods.price}}</p>
                        </a>
                        <section>
                            <button class="subShopping">-</button>
                            <span>{{cart.c_goods_num}}</span>
                            <button class="addShopping">+</button>
                        </section>

                    </li>
                {% endfor%}
            </ul>
            <li class="payTheBill">
                <div class="all_select">
                    <span>
                        {% if is_all_select %}
                        <span>√</span>
                        {% else %}
                        <span></span>
                        {% endif %}
                    </span>
                </div>
                <p>
                    <span>全选</span>
                    <span>共计:</span>
                    <span id="total_price">{{total_price}}</span>
                </p>
                <span id="make_order">下单</span>
            </li>
        </section>
    </div>
</div>

{% endblock %}

templates/home.html
{% extends 'base_main.html' %}
{% load static %}

{% block ext_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">
{% endblock %}

{% block ext_js %}
{{ block.super }}
<script type="text/javascript" src="{% static 'js/swiper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/js/home.js' %}"></script>
{% endblock %}

{% block content %}
<div id="home">
    {# 首页顶部轮播 #}
    <section class="swiper-container" id="topSwiper">
        <div class="swiper-wrapper">
            {% for main_wheel in main_wheels %}
            <div class="swiper-slide">
                <a href="#"><img src="{{main_wheel.img}}" alt="{{ main_wheel.name }}"/></a>
            </div>
            {% endfor %}
        </div>
        <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
    </section>


    <section class="topMenu">
        <nav>
            <ul>
                {% for main_nav in main_navs %}
                <li>
                    <a href="#">
                        <img src="{{main_nav.img}}" alt="{{main_nav.name }}"/>
                        <span>{{main_nav.name}}</span>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </nav>
        <menu class="swiper-container" id="swiperMenu">
            <ul class="swiper-wrapper">
                {% for main_mustbuy in main_mustbuys %}
                <li class="swiper-slide">
                    <a><img src="{{main_mustbuy.img}}"/></a>
                </li>
                {% endfor %}
            </ul>
        </menu>
    </section>

    <section class="CVS">
        <h2>
            <img src="{{main_shop0_1.0.img}}" alt="{{main_shop0_1.0.name}}"/>
        </h2>

        <fieldset>
            {% for x in main_shop1_3 %}
                <a href="#">
                    <img src="{{x.img}}" alt="{{x.name}}"/>
                </a>
            {% endfor %}
        </fieldset>

        <ul>
            {% for x in main_shop3_7 %}
                <li>
                    <a href="#">
                        <img src="{{x.img}}" />
                        <span>{{x.name}}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>

        <ol>
            {% for x in main_shop7_11 %}
                <li><a href="#"><img src="{{x.img}}" alt="{{x.name}}"/></a></li>
            {% endfor %}
        </ol>
    </section>

    <section class="mainInfo">
        {% for item in main_shows %}
            <section>
                <h3>
                    {{item.name}}
                    <a ui-sref="#">更多></a>
                    <span></span>
                </h3>
                <div>
                    <a href="#"><img src="{{item.img}}" alt="item.name"/></a>
                </div>
                <ul>
                    <li>
                        <a href="#">
                            <img src="{{item.img1}}"/>
                            <span class="description">{{item.longname1}}</span>
                            <span>¥{{item.price1}}</span>
                            <s>¥{{item.marketprice1}}</s>
                        </a>
                        <button><span>&#43;</span></button>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{{item.img2}}"/>
                            <span class="description">{{item.longname2}}</span>
                            <span>¥{{item.price2}}</span>
                            <s>¥{{item.marketprice2}}</s>
                        </a>
                        <button><span>&#43;</span></button>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{{item.img3}}"/>
                            <span class="description">{{item.longname3}}</span>
                            <span>¥{{item.price3}}</span>
                            <s>¥{{item.marketprice3}}</s>
                        </a>
                        <button><span>&#43;</span></button>
                    </li>
                </ul>
            </section>
        {% endfor %}
    </section>
</div>
{% endblock %}

templates/login.html
{% extends 'base_user.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'main/js/login.js' %}"></script>
{% endblock %}


{% block content %}
<div class="container">
    <form method="post" action="{% url 'sxw:login' %}" onsubmit="return parse_data()">

        {% csrf_token %}
        <p>{{error_message}}</p>

        <div class="form-group">
            <label for="username_input">用户名</label>
            <input name="username" type="text" class="form-control" id="username_input" placeholder="用户名/邮箱">
        </div>

        <div class="form-group">
            <label for="password_input">密码</label>
            <input name="password" type="password" class="form-control" id="password_input" placeholder="请输入密码">
        </div>


        <button type="submit" class="btn btn-success btn-block">登录</button>
    </form>
</div>
{% endblock%}

templates/market.html
{% extends 'base_main.html' %}
{% load static %}

{% block ext_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'main/css/market.css' %}">
{% endblock %}
{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'main/js/market.js'%}"></script>

{% endblock%}

{% block content %}
<div id="market">
    <aside>
        <ul>
            {% for foodtype in foodtypes %}
            <li>
                <a href="{% url 'sxw:market_with_params' typeid=foodtype.typeid childcid=0 order_rule=0 %}">
                    {{foodtype.typenames}}</a>
                {% ifequal foodtype.typeid typeid%}
                <span class="yellowSlide"></span>
                {% endifequal %}
            </li>
            {% endfor %}
        </ul>
    </aside>


    <section>
        <nav>
            <ul>
                <li><span id="all_types">全部类型<span class="glyphicon glyphicon-chevron-down"></span></span></li>
                <li><span id="sort_rule">综合排序<span class="glyphicon glyphicon-chevron-down"></span></span></li>
            </ul>
        </nav>

        <menu>
            <ul>
                {% for goods in goods_list %}
                <li>
                    <a href="#">
                        <img src="{{goods.productimg}}" alt="{{goods.productlongname}}"/>
                        <article class="shoppingInfo">
                            <h6>{{goods.productlongname}}</h6>
                            <p class="detailTag">
                                <span>精选</span>
                                <span>{{goods.pedesc}}</span>
                            </p>
                            <span class="unit">{{goods.specifics}}</span>
                            <p class="price">
                                <span>￥{{goods.price}}</span>
                                <s>
                                    <span>￥{{goods.marketprice}}</span>
                                </s>
                            </p>
                        </article>
                    </a>

                    <section>
                        <button goodsid="{{goods.id}}" class="subShopping">-</button>
                        <span>0</span>
						<button goodsid="{{goods.id}}" class="addShopping">+</button>
                    </section>
                </li>
                {% endfor%}
            </ul>
            <div id="all_types_container">
                <div>
                    {% for childname in childname_list %}
                    {% ifequal childname.1 childcid %}
                    <a href="{% url 'sxw:market_with_params' typeid=typeid childcid=childname.1 order_rule=0 %}">
                       <button class="btn btn-success">{{childname.0}}</button>
                    </a>
                    {% else %}
                    <a href="{% url 'sxw:market_with_params' typeid=typeid childcid=childname.1 order_rule=0 %}">
                       <button class="btn btn-default">{{childname.0}}</button>
                    </a>
                    {% endifequal %}
                    {% endfor %}

                </div>
            </div>

            <div id="sort_rule_container">
                <div>
                    {% for order_rule in order_rule_list %}
                    {% ifequal order_rule_view order_rule.1 %}
                    <a href="{% url 'sxw:market_with_params' typeid=typeid childcid=childcid order_rule=order_rule.1 %}">
                       <button class="btn btn-success">{{ order_rule.0 }}</button>
                    </a>
                    {% else %}
                    <a href="{% url 'sxw:market_with_params' typeid=typeid childcid=childcid order_rule=order_rule.1 %}">
                       <button class="btn btn-default">{{ order_rule.0 }}</button>
                    </a>
                    {% endifequal %}
                    {% endfor %}
                </div>
            </div>
        </menu>
    </section>


</div>
{% endblock%}

templates/mine.html
{% extends 'base_main.html' %}
{% load static %}

{% block ext_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'main/css/mine.css' %}">
{% endblock %}

{% block ext_js %}
{{ block.super }}
<script type="text/javascript" src="{% static 'main/js/mine.js' %}"></script>
{% endblock %}

{% block content %}
<div id="mine">
    <div class="fixed">
            <span>
                {% if is_login %}
                <img class="u_icon" src="{{icon}}" alt="{{username}}">
                {% else %}
                <span class="glyphicon glyphicon-user"></span>
                {% endif%}
            </span>
        {% if is_login %}
        <p>{{username}}</p>
        {% else %}
        <p id="not_login">未登录</p>
        {% endif%}
        <p>
            <span class="glyphicon glyphicon-fire"></span>
            <span>等级</span>
        </p>
        {% if not is_login %}
        <div id="regis">注册</div>
        {% endif%}
        <p>
            <span class="glyphicon glyphicon-heart"></span>
            <span>商品收藏</span>
        </p>
    </div>

    <div class="mine">
        <p>
            <span>全部订单</span>
            <a href="#">查看全部订单</a>
        </p>
        <nav id="nav">
            <ul>
                <li id="not_pay">
                    <dl>
                        {% ifnotequal order_not_pay 0 %}
                        <span class="badge">
                                {{order_not_pay}}
                        </span>
                            {% endifnotequal %}
                        <dt>
                            <span class="glyphicon glyphicon-usd"></span>
                        </dt>
                        <dd>待付款</dd>
                    </dl>
                </li>
                <li id="not_receive">
                    <dl>
                        {% ifnotequal order_not_receive 0 %}
                        <span class="badge">
                                {{order_not_receive}}
                        </span>
                            {% endifnotequal %}
                        <dt>
                            <span class="glyphicon glyphicon-envelope"></span>
                        </dt>
                        <dd>待收货</dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-pencil"></span>
                        </dt>
                        <dd>待评价</dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-retweet"></span>
                        </dt>
                        <dd>退款/售后</dd>
                    </dl>
                </li>
            </ul>
        </nav>
        <menu>
            <ul>
                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-bullhorn"></span>
                        </dt>
                        <dd>积分商城</dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-credit-card"></span>
                        </dt>
                        <dd>优惠券</dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-import"></span>
                        </dt>
                        <dd>收货地址</dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-phone-alt"></span>
                        </dt>
                        <dd>客服/反馈</dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-asterisk"></span>
                        </dt>
                        <dd>关于我们</dd>
                    </dl>
                </li>

            </ul>
        </menu>
        {% if is_login %}
        <p>
            <a href="{% url 'sxw:logout' %}">退出当前账号</a>
        </p>

        {% endif %}
    </div>
</div>

{% endblock %}

templates/order_detail.html
{% extends 'base_order.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'main/css/order_detail.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'main/js/order_detail.js' %}"></script>
{% endblock %}

{% block content %}
<div id="order_detail" class="container">
    <h6>订单编号：{{order.id}}</h6>
    <ul>
        {% for ordergoods in order.ordergoods_set.all %}
        <li>
            <img src="{{ordergoods.o_goods.productimg }}" alt="{{ordergoods.o_goods.productlongname}}">
        </li>
        {% endfor%}
    </ul>
    <ul>
        {% for ordergoods in order.ordergoods_set.all %}
        <li class="menulist">

            <a href="#">
                <img src="{{ ordergoods.o_goods.productimg }}" alt="{{ordergoods.o_goods.productlongname}}">
                <p>{{ordergoods.o_goods.productlongname }}</p>
                <p class="presentPrice">{{ordergoods.o_goods.price}}</p>
            </a>
            <section>

                <span>{{ordergoods.o_goods_num}}</span>

            </section>

        </li>
        {% endfor%}
    </ul>
    <h6  class="total_price">总价：<span id="total_price">{{order.o_price}}</span>></h6>
    <button orderid="{{order.id}}" id="alipay" class="btn btn-success btn-block">支付</button>
</div>
{% endblock %}

templates/order_list_not_pay.html
{% extends 'base_order.html' %}
{% load static %}

{% block ext_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'main/css/order_list_not_pay.css' %}">
{% endblock %}

{% block ext_js %}
{{ block.super }}
<script type="text/javascript" src="{% static 'main/js/order_list_not_pay.js' %}"></script>
{% endblock %}

{% block content %}
<div id="order_list_not_pay" class="container">
    <ol>
        {% for order in orders %}
        <li>
            <ul class="order" orderid="{{order.id}}">
                <h6>订单编号：{{order.id}}</h6>
                {% for ordergoods in order.ordergoods_set.all %}
                <li class="menulist">

                    <a href="#">
                        <img src="{{ ordergoods.o_goods.productimg }}" alt="{{ordergoods.o_goods.productlongname}}">
                        <p>{{ordergoods.o_goods.productlongname }}</p>
                        <p class="presentPrice">{{ordergoods.o_goods.price}}</p>
                    </a>
                    <section>

                        <span>{{ordergoods.o_goods_num}}</span>

                    </section>

                </li>
                {% endfor %}
            </ul>
        </li>
        {% endfor%}
    </ol>
</div>
{% endblock %}

templates/register.html
{% extends 'base_user.html' %}
{% load static %}

{% block ext_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'user/css/register.css' %}">
{% endblock %}

{% block ext_js %}
{{ block.super }}

<script type="text/javascript" src="{% static 'user/js/register.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data" action="{% url 'sxw:register' %}" onsubmit="return check()">

        {% csrf_token %}

        <div class="form-group">
            <label for="username_input">用户名</label>
            <input name="username" type="text" class="form-control" id="username_input" placeholder="请输入用户名">
            <span id="username_info"></span>
        </div>
        <div class="form-group">
            <label for="email_input">邮箱</label>
            <input name="email" type="text" class="form-control" id="email_input" placeholder="请输入邮箱">
        </div>
        <div class="form-group">
            <label for="password_input">密码</label>
            <input name="password" type="password" class="form-control" id="password_input" placeholder="请输入密码">
        </div>
        <div class="form-group">
            <label for="password_confirm_input">确认密码</label>
            <input type="password" class="form-control" id="password_confirm_input" placeholder="请确认密码">
        </div>
        <div class="form-group">
            <label for="icon_input">头像</label>
            <input name="icon" type="file" id="icon_input">
        </div>
        <button type="submit" class="btn btn-success btn-block">注册</button>
    </form>
</div>
{% endblock%}